### ISSUE TITLE
autobatching_max_keys typed as bool in create_client

### ISSUE THREAD

**Issue by kramar11** [emcache/emcache#101]
As the title says, in function `create_client` the parameter `autobatching_max_keys` is wrongly typed as `bool` instead of `int` (client.py:635). 

So mypy shows an error, e.g.
`error: Argument "autobatching_max_keys" to "create_client" has incompatible type "int"; expected "bool"  [arg-type]`

**Comment by pfreixes** [comment]
Could you provide a PR for fixing this? Thanks!
