### ISSUE TITLE
Request to clarify license

### ISSUE THREAD

**Issue by mgorven** [emcache/emcache#104]
The only indication of the license this code is released with is "Apache Software License" and "MIT License" listed in the PyPi metadata in `setup.py`. Would it be possible to add a `LICENSE` file with the exact license being used?

**Comment by mgorven** [comment]
Hi @pfreixes, thanks for the great memcache client. Would you mind having a look at this request? I have a PR I'd like to contribute with a bug fix, but I can't do so until we have clarity on the license.

**Comment by pfreixes** [comment]
Sorry for being so late in this one, we can go with a "MIT Licence", would you mind to make a PR with the necessary changes for clarifying the license model and add the LICENSE file?

Thanks!

**Comment by mgorven** [comment]
Great, PR is here: https://github.com/emcache/emcache/pull/108
