### ISSUE TITLE
OpTimeout needs to call `uncancel` in Python 3.11+ in order to actually suppress the cancellation

### ISSUE THREAD

**Issue by jhominal** [emcache/emcache#105]
As documented in https://docs.python.org/3.11/library/asyncio-task.html#asyncio.Task.cancel since Python 3.11, in order to actually suppress the cancellation of a task, one must, in addition to catching the `asyncio.CancelledError` exception, also call the `uncancel` method on the current task.

**Comment by pfreixes** [comment]
@jhominal its been a while since I did use asyncio and Python, could you help me to understand where will you will be calling `uncancel` and why?

**Comment by jhominal** [comment]
@pfreixes 

For the why, I would point to these bits of the Python documentation:

 * [This bit in the documentation for `asyncio.Task.cancel` lays out the requirement](https://docs.python.org/3.11/library/asyncio-task.html#asyncio.Task.cancel)
   > Should the coroutine nevertheless decide to suppress the cancellation, it needs to call [Task.uncancel()](https://docs.python.org/3.11/library/asyncio-task.html#asyncio.Task.uncancel) in addition to catching the exception.
 * [This bit in the documentation for `asyncio.Task.uncancel` describes exactly the pattern for which using `uncancel` is useful](https://docs.python.org/3.11/library/asyncio-task.html#asyncio.Task.uncancel);
   > In particular, if a Task gets successfully uncancelled, this allows for elements of structured concurrency like [Task Groups](https://docs.python.org/3.11/library/asyncio-task.html#taskgroups) and [asyncio.timeout()](https://docs.python.org/3.11/library/asyncio-task.html#asyncio.timeout) to continue running, isolating cancellation to the respective structured block

Here is the idea of the bug I have:

```python
try:
    with OpTimeout(timeout=0.1, loop=loop):
        await asyncio.sleep(1)
except asyncio.TimeoutError:
    pass

await unrelated_code()
```
In that code, because `OpTimeout` called `cancel` on the current task without an `uncancel` being called, `unrelated_code()` can raise `asyncio.CancelledError`. (The explanation being, that `cancel` marks the *task* as being canceled, and that mark is sticky until `uncancel` is called.)

I think you have two big ways of fixing this issue:

 1. Continue using `OpTimeout` on Python 3.11+, and call `uncancel` in `__aexit__`, here is my suggestion in https://github.com/emcache/emcache/blob/a85cc6fb23b7c6c168022a309ac9592eeb3f3ff5/emcache/timeout.py#L35-37

    ```diff
     async def __aexit__(self, exc_type, exc_value, traceback):
         if self._timed_out and (exc_type == asyncio.CancelledError):
+             if sys.python_version[:2] >= (3, 11):
+                 self._task.uncancel()
             # its not a real cancellation, was a timeout
-            raise asyncio.TimeoutError
+            raise asyncio.TimeoutError from None
```

 2. Replace `OpTimeout` with `asyncio.timeout` on Python 3.11+ - I think that may be the better long-term fix as it allows you to continue relying only on higher-level `asyncio` methods and, from what I can see, that method has the behavior you want;

**Comment by pfreixes** [comment]
Sorry for the late replay @jhominal, TBH its been a while since I worked with Python so Im gonna need to refresh a bit my mind on how things are done behind the scenes for allow me to understand how `uncancel` works and why its now required after 3.11

> In that code, because OpTimeout called cancel on the current task without an uncancel being called, unrelated_code() can raise asyncio.CancelledError. (The explanation being, that cancel marks the task as being canceled, and that mark is sticky until uncancel is called.)

Is this something that has changed after Python 3.11? so that any asynchronous code within a Task will get impacted from previous asynchronous code that was cancelled within the same task?

Jus saying because IIRC that was not the case in previous Python versions, where you could cancel a coroutine and then just swallow the exception and keep executing asynchronous code.

**Comment by jhominal** [comment]
Yes, `uncancel` was added in Python 3.11, at the same time as `asyncio.timeout` and `asyncio.TaskGroup`. (I believe the changes are linked)

As mentioned in the documentation for `uncancel`:

> If end-user code is, for some reason, suppressing cancellation by catching [CancelledError](https://docs.python.org/3.11/library/asyncio-exceptions.html#asyncio.CancelledError), it needs to call this method to remove the cancellation state.

**Comment by jhominal** [comment]
Yes, I can do that.

I think I should be able to write a PR along one of those lines:
 1. Modify `OpTimeout` so that it calls `asyncio.uncancel` are the right time if Python 3.11+ is in use;
 2. Modify `OpTimeout` so that it is basically a thin wrapper around `asyncio.timeout` on Python 3.11+;
 3. Replace usages of `OpTimeout` with `asyncio.timeout` if on Python 3.11+ and deprecate `OpTimeout`;
 
@pfreixes Which would you prefer as a maintainer?

**Comment by pfreixes** [comment]
Unfortunately I would advocate for giving still support for the 3.9 and 3.10 versions, both have between 2/3 years until the [EOL](https://devguide.python.org/versions/). So any solution would need to consider this.

So solution 1 might be the most compelling one Today and easy to implement.

**Comment by jhominal** [comment]
All of the proposed solutions consider compatibility with Python versions 3.8 to 3.10, the behavior would change only on Python 3.11+.

Personally I think using `asyncio.timeout` would allow `emcache` to get out of low-level `asyncio` business, which has the following advantages in my opinion:
 1. No change will be needed in `emcache` the next time there is a low-level breaking change in `asyncio`;
 2. While I *think* I understand how the call to `uncancel` should be done, I will admit that I would prefer using the higher-level facility for my own peace of mind, and ease of testing;

The only drawback of using `asyncio.timeout` is that it requires a “fork” in the code in order to maintain Python 3.8 to 3.10 compatibility.

This will be my last word on this point - if, after reading this, you still prefer that I add an `uncancel` call in `OpTimeout` in order to reduce code churn, I will do that. After all, you are the maintainer. (Sorry if I am bothering you with this discussion)

**Comment by pfreixes** [comment]
> The only drawback of using asyncio.timeout is that it requires a “fork” in the code in order to maintain Python 3.8 to 3.10 compatibility

What do you mean by a "fork"? if we can keep having compatibility for all Python versions 3.8 onwards Im happy with the solution but i would prefer if possible to not make a python version eval every time that we go through the code path that uses the timeout, like [here](https://github.com/emcache/emcache/blob/8152b12f9a9e66bbe3b93a252c9ac059296cba86/emcache/client.py#L161). So if this can be addressed in some way, Im happy to see using `asyncio.timeout` when it is available.

**Comment by jhominal** [comment]
By “fork”, I mean:

 * in the case of (2), it means having basically two implementations of `OpTimeout` - one for Python 3.11+ and one for previous Python versions;
 * In the case of (3), it means replacing direct calls to `OpTimeout` with a utility function that, depending on Python versions, will call either `OpTimeout` or `asyncio.timeout`;

**Comment by pfreixes** [comment]
Wondering if we could do something like this during loading time

```
if PYTHON_VERSION >= 3.11:
  timeout_cls = asyncio.timeout
else:
  timeout_cls  = OpTimeout
```

If Im not mistaken both have the same interfaces

**Comment by jhominal** [comment]
Yes, something like that should be possible, the interfaces are close enough for that.

**Comment by jhominal** [comment]
@pfreixes I have tried my hand at implementing this modification, and I would like your advice on a few points:

 * As `OpTimeout` is part of the exposed API of `emcache`, do you think that class, or a class with the same name, should be made fully functional on Python 3.11+?
 * In the case where you want to keep the `OpTimeout` class as part of the public API, available for callers, then there is the issue that `emcache.OpTimeout`'s initializer, like a lot of `emcache` objects, takes a `loop` argument, but `asyncio.timeout` does not. What should `emcache.OpTimeout` do if it is invoked with a `loop` argument that is not `asyncio.get_running_event_loop`?
   1. Work with the provided `loop` - that implies that `OpTimeout` needs to implement the calls to `asyncio.uncancel` itself;
   2. Ignore the provided `loop` and continue;
   3. Raise an exception that the provided `loop` cannot be used;

After looking at what to do, I am beginning to think that biting the bullet and modifying `OpTimeout` to call `uncancel` (and its friend `Task.cancelling`) is the less disruptive option to `emcache`.

**Comment by pfreixes** [comment]
I guess that there was never an intention on making public the `OpTimeout` class, my fault. We could have released a major version with the breaking changes, but its ok the way that you solved. Thanks for taking care of this

**Comment by jhominal** [comment]
Yes, I think that if you would like to transition to `asyncio.timeout` one day, it makes more sense to make a major version of `emcache` with more breaking changes:

 * support Python 3.11+ only;
 * Remove the `loop` arguments throughout `emcache` objects (`asyncio.get_running_loop` is used in every new `asyncio` API);
 * Replace `OpTimeout` with `asyncio.timeout`;
