### ISSUE TITLE
Timeout not working as expected

### ISSUE THREAD

**Issue by elbaro** [emcache/emcache#114]
```py
client = await emcache.create_client(
    [node], autobatching=True,autobatching_max_keys=128, min_connections=0, max_connections=32
)

        import time
        t = time.time()
        try:
          async with asyncio.timeout(3):
            item = await client.gets(key, return_flags=return_flags)
        except asyncio.TimeoutError:
            print(time.time() -t, ' seconds elapsed')
            print('timeout mc key: ', key)
            mg=client.cluster_managment()
            print(mg.unhealthy_nodes())
            print(mg.connection_pool_metrics())
```

The client is supposed to have the default timeout of 1 second. However the exception is raised after 3 seconds.

```
3.001142740249634  seconds elapsed
timeout mc key:  b'..'
[]
{MemcachedHostAddress(address='mc276', port=11211): ConnectionPoolMetrics(cur_connections=1, connections_created=1, connections_created_with_error=0, connections_purged=0, connections_closed=0, operations_executed=16, operations_executed_with_error=0, operations_waited=1, create_connection_avg=0.0011269636452198029, create_connection_p50=0.0011269636452198029, create_connection_p99=0.0011269636452198029, create_connection_upper=0.0011269636452198029)}
```

Also, the connetion time is fast and the key is not large. It looks like a deadlock somewhere in emcache.

**Comment by elbaro** [comment]
This is Python 3.11 and all usage of OpTimeout is already replaced by asyncio.timeout as suggested in #105.

**Comment by pfreixes** [comment]
Does this happen when you are not using `autobatching`? if not this might indicate a bug with the `autobatching` feature. I would need to debug and fix the issue, but I have limited time. Is there any chance that you could dig more into it and check what could be the reason on not having the timeout being raised?

**Comment by elbaro** [comment]
@pfreixes Sorry, closing this.

We quickly migrated to aiomcache and found out-of-open-file logs, increased the limit, and there has been no timeout anymore.
However we didn't manage to go back to emcache and confirm again with emcache + increased nofile limit.
