### ISSUE TITLE
incorrect impl method `get`

### ISSUE THREAD

**Issue by ArtemIsmagilov** [emcache/emcache#120]
Client using get method
returns only one result, which is not entirely true. According to the protocol, you can specify several keys and obtain several values. I would like to add a little to this feature.

https://github.com/memcached/memcached/blob/9dc8b148345b27dd86580641d17f4268885b5894/doc/protocol.txt#L293

**Comment by ArtemIsmagilov** [comment]
so, im sorry, you impl in `get_many`)
https://github.com/emcache/emcache/blob/449dad934ab81d5b821a9b19c9fb92f8cacb17a0/emcache/client.py#L315

**Comment by ArtemIsmagilov** [comment]
please, remove this issue

**Comment by pfreixes** [comment]
No problemo.
