### ISSUE TITLE
Support for SASL authentication

### ISSUE THREAD

**Issue by pfreixes** [emcache/emcache#60]
Provide a mechanism for authenticating against the Memcached servers. Before needed support for the binary protocol.

**Comment by ArtemIsmagilov** [comment]
well, I accidentally didn’t read about this problem and made a copy 
 #125

**Comment by ArtemIsmagilov** [comment]
macos does not yet support SASL on its part

**Comment by pfreixes** [comment]
Closing this ones as done, it supports Linux which is what is being used in production. Also most of people uses Memcache dockerized when runnning in local
