### ISSUE TITLE
emcache.create_client does not need to be async

### ISSUE THREAD

**Issue by vmarkovtsev** [emcache/emcache#63]
As I see in the code of `emcache.create_client`, the function does not have to be async. I am porting from `aiomcache` where `aiomcache.Client()` is not async, so I am having some troubles.

**Comment by pfreixes** [comment]
Hi @vmarkovtsev thanks for opening the issue.

Making the `create_client` as an asynchronous factory was done in propose, and despite does not wait for any asynchronous application behind the scenes there are many places where there is an expectation that the loop should be spinning like this [1] and this [2].


[1] https://github.com/emcache/emcache/blob/master/emcache/connection_pool.py#L150
[2] https://github.com/emcache/emcache/blob/master/emcache/connection_pool.py#L139

**Comment by vmarkovtsev** [comment]
I see `self._loop = asyncio.get_running_loop()`, yes. How about replacing it with `asyncio.get_event_loop` instead.

**Comment by vmarkovtsev** [comment]
That's a pity, then I have to fork aiomcache after all.

BTW regarding the loop provided by the caller, that's [an officially deprecated asyncio practice](https://stackoverflow.com/questions/60312374/what-are-all-these-deprecated-loop-parameters-in-asyncio). You probably meant smth different.

Cheers from Madrid! We are using Auth0 :smile:
