### ISSUE TITLE
Feature request: support `version` command

### ISSUE THREAD

**Issue by vmarkovtsev** [emcache/emcache#64]
aiomcache allows getting the server's version. How about adding `_Client.version()`?

**Comment by pfreixes** [comment]
Hi @vmarkovtsev thanks for the proposal.

I do not see any any issue by having a new method for returning the version of the memcached server, it´s only a matter of doing the proper wiring for this new function. 

PR are more than welcomed!

PD: Eventually we will have support for the binary protocol - next major release - and this will force us to implement methods for both protocols.

**Comment by ArtemIsmagilov** [comment]
I think we can close this problem, there is support for the version command(#118 )

**Comment by pfreixes** [comment]
Yeps, closing it right now
