### ISSUE TITLE
Don't log when connection lost as part of purge of unused connections

### ISSUE THREAD

**Issue by calpaterson** [emcache/emcache#65]
I don't think a connection lost (for example as unused connections are purged) is necessarily serious enough to emit a `WARNING` level log about - it's completely routine and expected behavior.  As it stands this log creates unwanted noise and I currently filter it.

Perhaps it could be `INFO` or `DEBUG` level?

https://github.com/emcache/emcache/blob/3a35b9ea87ebc02ed6df2a33aa78199ef9ba8f36/emcache/protocol.py#L57

Thanks for open sourcing this!  Very useful for a side-project of mine

**Comment by pfreixes** [comment]
I guess that we could check if the connection was already explicitly close by us by making a check if `_closed` is True or Not. We could just make the logging if and only if the `_closed` was set to False.

Any chance to have a PR from you @calpaterson ?

**Comment by pfreixes** [comment]
addressed in #73
