### ISSUE TITLE
Support for new Mac M1 chips

### ISSUE THREAD

**Issue by pfreixes** [emcache/emcache#67]
Current CI Build only provides wheels for older Macs with x86 architecture, new Macs are based on ARM chips. We would need to change the current CI build for publishing also wheels for new Macs

For doing so we could use the new cibuildweel project [1], an example of its usage here [2]

[1] https://cibuildwheel.readthedocs.io/en/stable/
[2] https://github.com/MagicStack/uvloop/blob/3f691ab2a16bd6920a9d99ab6a25a4fd1c6f391f/.github/workflows/release.yml#L111

**Comment by ferpizza** [comment]
+1

**Comment by odidev** [comment]
I was testing **limits** on Linux aarch64 architecture, but it is failing due to **emcache** dependency. As there is no source code link on [pypi](https://pypi.org/project/emcache/#files) for emcache. I tried through pip but it does not support to build on aarch64 architectures
It would be really helpful if  linux aarch64 wheels could be released to pypi.
Related to [#116](url) @ Pau Freixes Could you please share your views regarding this?

**Comment by pfreixes** [comment]
We would need the way that the wheels are built, while is not rocket science its tedius work that requires sime time, if some of you want to work on it would be awesome.

**Comment by odidev** [comment]
That would be great. I would be happy to work on building wheels for emcache. Please let me know how to proceed since there is no source code accessible to me.

**Comment by odidev** [comment]
@[pfreixes](https://github.com/pfreixes) could u pls share your feedback regarding this?

**Comment by pfreixes** [comment]
@odidev hi, sorry for the late replay.

Unless Im missing something the issue already describes how this should be tackled, current build is basically done by hand running this script [1] through this step [2].

Be careful these are the steps for Linux wheels, for Mac is slightly easier you can find the build process here [3]. 

The original description of the issue says

> Current CI Build only provides wheels for older Macs with x86 architecture, new Macs are based on ARM chips. We would need to change the current CI build for publishing also wheels for new Macs
For doing so we could use the new cibuildweel project [1], an example of its usage here [2]

The `cibuildweel` project from my understanding removes all of the complexity that we had to add for building specific builds for each arch, so we could eventually replace the current implementation for using specifically this project, not sure if we could add a patch in the current system for addressing this specifically issue without having to change everything.



[1] https://github.com/emcache/emcache/blob/master/bin/build_manylinux1_wheel.sh
[2] https://github.com/emcache/emcache/blob/master/.github/workflows/release.yml#L38
[3] https://github.com/emcache/emcache/blob/master/.github/workflows/release.yml#L23

**Comment by JoshCLWren** [comment]
Any news on this? This is a constant pain point for me and my teammates.

**Comment by Hazealign** [comment]
Can I take this issue? I'll make PR for murmur3 and emcache both.

**Comment by pfreixes** [comment]
@Hazealign please go ahead! one from murmur already merged

**Comment by Hazealign** [comment]
I successfully create universal2/arm64 wheel and test universal2 wheel in GitHub Actions. (But it's draft branch. It's very dirty. LOL)
I'll make another clean branch for make PR. And Separate macOS and Linux's build.

![image](https://user-images.githubusercontent.com/1115741/182047189-0eee949c-4a23-4634-8de1-56a3ffadf24d.png)
