### ISSUE TITLE
Pypi release for python 3.10

### ISSUE THREAD

**Issue by alisaifee** [emcache/emcache#70]
I'd like to request a release for python 3.10 on pypi.
I was able to compile and install the package atleast and do some light testing on python 3.10.1 + linux

**Comment by pfreixes** [comment]
Seems that its not straight forward, or at least tests are not passing PTLAL here https://github.com/emcache/emcache/runs/4669753399?check_suite_focus=true.

Im short of time, any chance on having some of you investigating the issue? /cc @alisaifee

**Comment by pfreixes** [comment]
Finally Ive managed to fix the issue, you should be able to download a 3.10 compatible version of emcache using the latest 0.6.1 version, through https://pypi.org/project/emcache

Let me know if there is any issue
