### ISSUE TITLE
Key validation disallows allowed characters

### ISSUE THREAD

**Issue by justin-richert** [emcache/emcache#74]
It would appear to me that there are some characters being disallowed in key validation that should be allowed. For example ñ (`\xd1`) fails the check in `is_key_valid`:

```python
>>> from emcache.client import cyemcache
>>> cyemcache.is_key_valid(b'\xd1')
False
```

But the memcache protocol documentation seems to indicate that this character should be fine:
> Data stored by memcached is identified with the help of a key. A key
is a text string which should uniquely identify the data for clients
that are interested in storing and retrieving it.  Currently the
length limit of a key is set at 250 characters (of course, normally
clients wouldn't need to use such long keys); the key must not include
control characters or whitespace

(From https://github.com/memcached/memcached/blob/master/doc/protocol.txt)

ñ is neither a control character or whitespace which is what leads me to believe it should be acceptable. Telnetting to an instance of memcache and bypassing `emcache` successfully allows this as well:
```
set \xd1 0 100 4
test
STORED
get \xd1
test
```

Of course, let me know if I'm misunderstanding something here. Also happy to contribute an attempt at a fix if that's welcome!

**Comment by pfreixes** [comment]
Yeps, you are totally right, we can follow just this [1]

Any chance to have a PR from you for fixing this? Thanks!


[1] https://github.com/bradfitz/gomemcache/blob/fb4bf637b56d66a1925c1bb0780b27dd714ec380/memcache/memcache.go#L94

**Comment by justin-richert** [comment]
@pfreixes Yep, I'll get something put together for you as soon as I can!
