### ISSUE TITLE
Release next version for support arm64 in macOS.

### ISSUE THREAD

**Issue by Hazealign** [emcache/emcache#76]
Can we release next version for support Apple Silicon?
If changes are insufficient, I think we can build v0.6.1 again just with macOS build.

p.s. I'll try to use cibuildwheel for Linux too. And also this makes to support arm64(aarch64) Architecture's wheels in Linux too.

Thanks. :)

**Comment by pfreixes** [comment]
Hi @Hazealign seems the pipeline got broken for publishing new images, see error that we are getting here [1] any chance for taking it a look? Once fixed I can delete the tag and give it a second try

[1] https://github.com/emcache/emcache/runs/7753510309?check_suite_focus=true

**Comment by Hazealign** [comment]
I'm really Sorry @pfreixes. I'll make quickfix PR in just today(on KST).

**Comment by Hazealign** [comment]
I can't allocate my time. @pfreixes I'll try at this Saturday morning. I apologize for this issue.

**Comment by pfreixes** [comment]
Not a problem, not in a rush

**Comment by Hazealign** [comment]
Handling this issue now.

**Comment by pfreixes** [comment]
Merged but still having issues here https://github.com/emcache/emcache/runs/7973903762?check_suite_focus=true#step:6:13 ... any chance that you could take a look?

**Comment by Hazealign** [comment]
@pfreixes that's weird. emcache binaries are uploaded and downloaded well as expected. I'll check it.

<img width="2614" alt="image" src="https://user-images.githubusercontent.com/1115741/186586275-1a306d4f-fc09-4a18-aec5-47d54c61e0df.png">

**Comment by pfreixes** [comment]
@Hazealign can be this closed?
