### ISSUE TITLE
Unable to install emcache on Windows 11

### ISSUE THREAD

**Issue by dmdhrumilmistry** [emcache/emcache#80]
I'm trying to install emcache on Windows 11, but it returns error saying No matching distribution found.

```Powershell
PS C:\> pip install emcache
ERROR: Could not find a version that satisfies the requirement emcache (from versions: none)
ERROR: No matching distribution found for emcache
```

Am I missing something?

**Comment by pfreixes** [comment]
Hi, sorry but there is no Windows distribution, and its unlikely that we could built a weel for it Today

**Comment by dmdhrumilmistry** [comment]
@pfreixes thank your for the clarification 👍🏻
