### ISSUE TITLE
Proposing as a maintainer Haze Lee

### ISSUE THREAD

**Issue by pfreixes** [emcache/emcache#82]
I would like to propose as a maintainer @Hazealign, already gave you write permissions for pushing to the repository but considering the work done for improving the CI I would like you to also give you the maintainer role.

WDYT?

**Comment by Hazealign** [comment]
Yes. I'll keep improve CI. (also with linux too) I'll make some time for maintain. Thanks.

**Comment by Hazealign** [comment]
I'll make some plans for improving CI pipelines.

**Comment by Hazealign** [comment]
#85 will be detail action plans. I'll start it. :)

**Comment by pfreixes** [comment]
Added as a mantainer, wellcome!
